// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '1. Guida Utente',
      link: {type: 'doc', id: 'utente/overview'},
      items: [
        {
          type: 'category',
          label: 'Navigazione',
          link: {type: 'doc', id: 'utente/navigazione'},
          items: [
            {
              type: 'category',
              label: 'Menu laterale sinistro',
              link: {type: 'doc', id: 'utente/navigazione-menu-laterale'},
              items: [
                'utente/navigazione-menu-laterale-overview',
                'utente/navigazione-menu-laterale-users',
                'utente/navigazione-menu-laterale-api-key',
                'utente/navigazione-menu-laterale-logs',
                'utente/navigazione-menu-laterale-alertmanager-creare-alert',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Flusso di lavoro',
          link: {type: 'doc', id: 'utente/flusso-di-lavoro'},
          items: [
            'utente/fase-1-universe',
            'utente/fase-2-indicatori',
            'utente/fase-3-filtro',
            'utente/fase-4-ranking',
            'utente/fase-5-decision-engine',
            'utente/fase-6-live-update',
            'utente/fase-7-live-order',
          ],
        },
        'utente/mcp-gateway',
        {
          type: 'category',
          label: 'Servizi a supporto',
          items: [
            {
              type: 'category',
              label: 'capital-manager',
              link: {type: 'doc', id: 'utente/servizi-a-supporto/capital-manager'},
              items: [
                'utente/servizi-a-supporto/capital-manager-allocazione',
                'utente/servizi-a-supporto/capital-manager-prenotazioni',
                'utente/servizi-a-supporto/capital-manager-parametri',
              ],
            },
            {
              type: 'category',
              label: 'liquidity-manager',
              link: {type: 'doc', id: 'utente/servizi-a-supporto/liquidity-manager'},
              items: [
                'utente/servizi-a-supporto/liquidity-manager-fonti-dati',
                'utente/servizi-a-supporto/liquidity-manager-calcoli',
              ],
            },
            {
              type: 'category',
              label: 'alertmanager',
              link: {type: 'doc', id: 'utente/servizi-a-supporto/alertmanager'},
              items: [
                'utente/servizi-a-supporto/alertmanager-catalogo-eventi',
              ],
            },
            'utente/servizi-a-supporto/ibkr-login-desktop',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '2. Developer',
      link: {type: 'doc', id: 'developer-esterno-api/overview'},
      items: [
        {
          type: 'category',
          label: 'Deployment',
          link: {type: 'doc', id: 'developer-esterno-api/deployment'},
          items: [
            'developer-esterno-api/deployment-variabili-ambiente',
            {
              type: 'category',
              label: 'Git Deployment',
              link: {type: 'doc', id: 'developer-esterno-api/deployment-git'},
              items: [
                'developer-esterno-api/deployment-local-to-paper',
                'developer-esterno-api/deployment-git-trading-system-cicd',
                'developer-esterno-api/deployment-git-astraai-cicd',
                'developer-esterno-api/deployment-git-operativo-commit-pipeline',
                'developer-esterno-api/deployment-git-versioning-tag',
                'developer-esterno-api/deployment-git-rollback-stabile',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Frontend',
          link: {type: 'doc', id: 'developer-esterno-api/frontend'},
          items: [
            'developer-esterno-api/frontend-architettura',
            'developer-esterno-api/frontend-componenti',
            'developer-esterno-api/frontend-servizi',
            'developer-esterno-api/frontend-pagine',
          ],
        },
        {
          type: 'category',
          label: 'Backend',
          link: {type: 'doc', id: 'developer-esterno-api/backend'},
          items: [
            'developer-esterno-api/tools',
            {
              type: 'category',
              label: 'Shared Library',
              link: {type: 'doc', id: 'developer-esterno-api/shared-library'},
              items: [
                'developer-esterno-api/shared-base-service',
                'developer-esterno-api/shared-server-factory',
                'developer-esterno-api/shared-status-router-factory',
                'developer-esterno-api/shared-logger',
                'developer-esterno-api/shared-load-settings',
                'developer-esterno-api/shared-redis-bus',
                'developer-esterno-api/shared-events-manifest-registry',
                'developer-esterno-api/shared-redis-publisher',
                'developer-esterno-api/shared-job-reporter',
                'developer-esterno-api/shared-internal-auth',
                'developer-esterno-api/shared-datahub-adapter',
                'developer-esterno-api/shared-routes-loader',
                'developer-esterno-api/shared-helpers',
                'developer-esterno-api/shared-cache',
                'developer-esterno-api/shared-text-resolver',
                'developer-esterno-api/shared-trade-db-helpers',
                'developer-esterno-api/shared-alpaca',
                'developer-esterno-api/shared-strategy-utils',
              ],
            },
            {
              type: 'category',
              label: 'Microservizi',
              link: {type: 'doc', id: 'developer-esterno-api/microservizi'},
              items: [
                {
                  type: 'category',
                  label: 'Microservizi a supporto',
                  items: [
                    'developer-esterno-api/ms-traefik',
                    'developer-esterno-api/ms-mysql',
                    'developer-esterno-api/ms-redis',
                    'developer-esterno-api/ms-ibkrgw-paper',
                  ],
                },
                {
                  type: 'category',
                  label: 'Microservizi specifici',
                  items: [
                    {
                      type: 'category',
                      label: 'datahub',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-datahub'},
                      items: [
                        'developer-esterno-api/ms-datahub-architettura',
                        'developer-esterno-api/ms-datahub-endpoint',
                        'developer-esterno-api/ms-datahub-file-e-ruoli',
                        'developer-esterno-api/ms-datahub-configurazione',
                        'developer-esterno-api/ms-datahub-runbook',
                        'developer-esterno-api/ms-datahub-endpoint-automatici',
                        'developer-esterno-api/ms-datahub-endpoint-interni',
                        'developer-esterno-api/ms-datahub-endpoint-manuali',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'authservice',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-authservice'},
                      items: [
                        'developer-esterno-api/ms-authservice-architettura',
                        'developer-esterno-api/ms-authservice-endpoint',
                        'developer-esterno-api/ms-authservice-file-e-ruoli',
                        'developer-esterno-api/ms-authservice-configurazione',
                        'developer-esterno-api/ms-authservice-runbook',
                        'developer-esterno-api/ms-authservice-traefik',
                        'developer-esterno-api/ms-authservice-autenticazione-interna',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'cachemanager',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-cachemanager'},
                      items: [
                        'developer-esterno-api/ms-cachemanager-architettura',
                        'developer-esterno-api/ms-cachemanager-endpoint',
                        'developer-esterno-api/ms-cachemanager-file-e-ruoli',
                        'developer-esterno-api/ms-cachemanager-configurazione',
                        'developer-esterno-api/ms-cachemanager-runbook',
                        'developer-esterno-api/ms-cachemanager-limiti-cache',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'decision-engine',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-decision-engine'},
                      items: [
                        'developer-esterno-api/ms-decision-engine-architettura',
                        'developer-esterno-api/ms-decision-engine-endpoint',
                        'developer-esterno-api/ms-decision-engine-file-e-ruoli',
                        'developer-esterno-api/ms-decision-engine-configurazione',
                        'developer-esterno-api/ms-decision-engine-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'market-data-service',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-market-data-service'},
                      items: [
                        'developer-esterno-api/ms-market-data-service-architettura',
                        'developer-esterno-api/ms-market-data-service-endpoint',
                        'developer-esterno-api/ms-market-data-service-file-e-ruoli',
                        'developer-esterno-api/ms-market-data-service-configurazione',
                        'developer-esterno-api/ms-market-data-service-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'redis-ws-bridge',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-redis-ws-bridge'},
                      items: [
                        'developer-esterno-api/ms-redis-ws-bridge-architettura',
                        'developer-esterno-api/ms-redis-ws-bridge-endpoint',
                        'developer-esterno-api/ms-redis-ws-bridge-file-e-ruoli',
                        'developer-esterno-api/ms-redis-ws-bridge-configurazione',
                        'developer-esterno-api/ms-redis-ws-bridge-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'ibkr-bridge',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-ibkr-bridge'},
                      items: [
                        'developer-esterno-api/ms-ibkr-bridge-architettura',
                        'developer-esterno-api/ms-ibkr-bridge-endpoint',
                        'developer-esterno-api/ms-ibkr-bridge-file-e-ruoli',
                        'developer-esterno-api/ms-ibkr-bridge-configurazione',
                        'developer-esterno-api/ms-ibkr-bridge-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'ibkr-keepalive',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-ibkr-keepalive'},
                      items: [
                        'developer-esterno-api/ms-ibkr-keepalive-architettura',
                        'developer-esterno-api/ms-ibkr-keepalive-endpoint',
                        'developer-esterno-api/ms-ibkr-keepalive-file-e-ruoli',
                        'developer-esterno-api/ms-ibkr-keepalive-configurazione',
                        'developer-esterno-api/ms-ibkr-keepalive-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'alertingservice',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-alertingservice'},
                      items: [
                        'developer-esterno-api/ms-alertingservice-architettura',
                        'developer-esterno-api/ms-alertingservice-endpoint',
                        'developer-esterno-api/ms-alertingservice-file-e-ruoli',
                        'developer-esterno-api/ms-alertingservice-configurazione',
                        'developer-esterno-api/ms-alertingservice-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'scheduler',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-scheduler'},
                      items: [
                        'developer-esterno-api/ms-scheduler-architettura',
                        'developer-esterno-api/ms-scheduler-endpoint',
                        'developer-esterno-api/ms-scheduler-file-e-ruoli',
                        'developer-esterno-api/ms-scheduler-configurazione',
                        'developer-esterno-api/ms-scheduler-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'tickerscanner',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-tickerscanner'},
                      items: [
                        'developer-esterno-api/ms-tickerscanner-architettura',
                        'developer-esterno-api/ms-tickerscanner-endpoint',
                        'developer-esterno-api/ms-tickerscanner-file-e-ruoli',
                        'developer-esterno-api/ms-tickerscanner-configurazione',
                        'developer-esterno-api/ms-tickerscanner-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'servicecontrolplane',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-servicecontrolplane'},
                      items: [
                        'developer-esterno-api/ms-servicecontrolplane-architettura',
                        'developer-esterno-api/ms-servicecontrolplane-endpoint',
                        'developer-esterno-api/ms-servicecontrolplane-file-e-ruoli',
                        'developer-esterno-api/ms-servicecontrolplane-configurazione',
                        'developer-esterno-api/ms-servicecontrolplane-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'broker-executor-ibkr',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-brokerexecutor-ibkr'},
                      items: [
                        'developer-esterno-api/ms-brokerexecutor-ibkr-architettura',
                        'developer-esterno-api/ms-brokerexecutor-ibkr-endpoint',
                        'developer-esterno-api/ms-brokerexecutor-ibkr-file-e-ruoli',
                        'developer-esterno-api/ms-brokerexecutor-ibkr-configurazione',
                        'developer-esterno-api/ms-brokerexecutor-ibkr-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'liquidity-manager',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-liquidity-manager'},
                      items: [
                        'developer-esterno-api/ms-liquidity-manager-architettura',
                        'developer-esterno-api/ms-liquidity-manager-endpoint',
                        'developer-esterno-api/ms-liquidity-manager-file-e-ruoli',
                        'developer-esterno-api/ms-liquidity-manager-configurazione',
                        'developer-esterno-api/ms-liquidity-manager-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'mcp-gateway',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-mcp-gateway'},
                      items: [
                        'developer-esterno-api/ms-mcp-gateway-architettura',
                        'developer-esterno-api/ms-mcp-gateway-endpoint',
                        'developer-esterno-api/ms-mcp-gateway-file-e-ruoli',
                        'developer-esterno-api/ms-mcp-gateway-configurazione',
                        'developer-esterno-api/ms-mcp-gateway-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'capital-manager',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-capital-manager'},
                      items: [
                        'developer-esterno-api/ms-capital-manager-architettura',
                        'developer-esterno-api/ms-capital-manager-endpoint',
                        'developer-esterno-api/ms-capital-manager-file-e-ruoli',
                        'developer-esterno-api/ms-capital-manager-configurazione',
                        'developer-esterno-api/ms-capital-manager-runbook',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'market-simulator',
                      link: {type: 'doc', id: 'developer-esterno-api/ms-market-simulator'},
                      items: [
                        'developer-esterno-api/ms-market-simulator-architettura',
                        'developer-esterno-api/ms-market-simulator-endpoint',
                        'developer-esterno-api/ms-market-simulator-file-e-ruoli',
                        'developer-esterno-api/ms-market-simulator-configurazione',
                        'developer-esterno-api/ms-market-simulator-runbook',
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '3. Amministratore',
      link: {type: 'doc', id: 'amministratore/overview'},
      items: [{type: 'autogenerated', dirName: '03-amministratore'}],
    },
    {
      type: 'category',
      label: '4. API',
      link: {type: 'doc', id: 'developer-interno/overview'},
      items: [
        'developer-interno/mappa-cartelle',
        'developer-interno/messages',
        'developer-interno/servizi/overview',
        {
          type: 'category',
          label: 'authservice',
          link: {type: 'doc', id: 'developer-interno/servizi/authservice'},
          items: [
            'developer-interno/servizi/authservice-endpoint-01-post-auth-login',
            'developer-interno/servizi/authservice-endpoint-02-post-auth-renew',
            'developer-interno/servizi/authservice-endpoint-03-get-auth-validate',
            'developer-interno/servizi/authservice-endpoint-04-get-auth-admin-me',
            'developer-interno/servizi/authservice-endpoint-05-get-auth-admin-user',
            'developer-interno/servizi/authservice-endpoint-06-get-auth-admin-user-id',
            'developer-interno/servizi/authservice-endpoint-07-post-auth-admin-user',
            'developer-interno/servizi/authservice-endpoint-08-put-auth-admin-user-id',
            'developer-interno/servizi/authservice-endpoint-09-delete-auth-admin-user-id',
            'developer-interno/servizi/authservice-endpoint-10-get-auth-admin-user-id-permissions',
            'developer-interno/servizi/authservice-endpoint-11-post-auth-admin-user-id-permissions',
            'developer-interno/servizi/authservice-endpoint-12-put-auth-admin-user-id-permissions-permid',
            'developer-interno/servizi/authservice-endpoint-13-delete-auth-admin-user-id-permissions-permid',
            'developer-interno/servizi/authservice-endpoint-14-get-auth-admin-api-keys',
            'developer-interno/servizi/authservice-endpoint-15-post-auth-admin-api-keys',
            'developer-interno/servizi/authservice-endpoint-16-put-auth-admin-api-keys-id',
            'developer-interno/servizi/authservice-endpoint-17-delete-auth-admin-api-keys-id',
          ],
        },
        {
          type: 'category',
          label: 'datahub',
          link: {type: 'doc', id: 'developer-interno/servizi/datahub'},
          items: [
            'developer-interno/servizi/datahub-endpoint-01-get-datahub-api-schema',
            'developer-interno/servizi/datahub-endpoint-02-post-datahub-api-refresh',
            'developer-interno/servizi/datahub-endpoint-03-get-datahub-api-caching',
            'developer-interno/servizi/datahub-endpoint-04-get-datahub-api-caching-tablename',
            'developer-interno/servizi/datahub-endpoint-05-put-datahub-api-caching-tablename',
            'developer-interno/servizi/datahub-endpoint-06-get-datahub-api-table-tablename',
            'developer-interno/servizi/datahub-endpoint-07-get-datahub-api-table-tablename-pk',
            'developer-interno/servizi/datahub-endpoint-08-post-datahub-api-table-tablename',
            'developer-interno/servizi/datahub-endpoint-09-put-datahub-api-table-tablename-pk',
            'developer-interno/servizi/datahub-endpoint-10-delete-datahub-api-table-tablename-pk',
            'developer-interno/servizi/datahub-endpoint-11-all-datahub-api-custom',
            'developer-interno/servizi/datahub-endpoint-12-get-datahub-auth-users',
            'developer-interno/servizi/datahub-endpoint-13-get-datahub-auth-users-id',
            'developer-interno/servizi/datahub-endpoint-14-post-datahub-auth-users',
            'developer-interno/servizi/datahub-endpoint-15-put-datahub-auth-users-id',
            'developer-interno/servizi/datahub-endpoint-16-delete-datahub-auth-users-id',
          ],
        },
        {
          type: 'category',
          label: 'cachemanager',
          link: {type: 'doc', id: 'developer-interno/servizi/cachemanager'},
          items: [
            'developer-interno/servizi/cachemanager-endpoint-01-get-cachemanager-candles',
            'developer-interno/servizi/cachemanager-endpoint-02-get-cachemanager-l2-file',
            'developer-interno/servizi/cachemanager-endpoint-03-put-cachemanager-l2-file',
            'developer-interno/servizi/cachemanager-endpoint-04-get-cachemanager-l2-audit',
            'developer-interno/servizi/cachemanager-endpoint-05-post-cachemanager-l2-clear',
            'developer-interno/servizi/cachemanager-endpoint-06-get-cachemanager-provider',
            'developer-interno/servizi/cachemanager-endpoint-07-put-cachemanager-provider-provider',
            'developer-interno/servizi/cachemanager-endpoint-08-get-cachemanager-status-l2-size',
            'developer-interno/servizi/cachemanager-endpoint-09-delete-cachemanager-status-l2-size-symbol-da',
            'developer-interno/servizi/cachemanager-endpoint-10-get-cachemanager-status-l3-size',
            'developer-interno/servizi/cachemanager-endpoint-11-delete-cachemanager-status-l3-size-symbol-tf',
          ],
        },
        {
          type: 'category',
          label: 'decision-engine',
          link: {type: 'doc', id: 'developer-interno/servizi/decision-engine'},
          items: [
            'developer-interno/servizi/decision-engine-endpoint-01-get-decision-engine-spot-finder',
            'developer-interno/servizi/decision-engine-endpoint-02-get-decision-engine-spot-finder-pipeid',
            'developer-interno/servizi/decision-engine-endpoint-03-post-decision-engine-spot-finder-pipeid',
            'developer-interno/servizi/decision-engine-endpoint-04-get-decision-engine-spot-finder-jobs-jobid',
            'developer-interno/servizi/decision-engine-endpoint-05-post-decision-engine-spot-finder-jobs-jobid-',
            'developer-interno/servizi/decision-engine-endpoint-06-get-decision-engine-spot-finder-latest-pipei',
            'developer-interno/servizi/decision-engine-endpoint-07-post-decision-engine-spot-finder-live-pipeid',
            'developer-interno/servizi/decision-engine-endpoint-08-get-decision-engine-spot-finder-live-pipeid',
            'developer-interno/servizi/decision-engine-endpoint-09-get-decision-engine-spot-finder-live-pipeid-',
            'developer-interno/servizi/decision-engine-endpoint-10-delete-decision-engine-spot-finder-live-pipe',
            'developer-interno/servizi/decision-engine-endpoint-11-post-decision-engine-internal-spot-finder-pi',
            'developer-interno/servizi/decision-engine-endpoint-12-post-decision-engine-internal-spot-finder-li',
            'developer-interno/servizi/decision-engine-endpoint-13-delete-decision-engine-internal-spot-finder-',
          ],
        },
        {
          type: 'category',
          label: 'market-data-service',
          link: {type: 'doc', id: 'developer-interno/servizi/market-data-service'},
          items: [
            'developer-interno/servizi/market-data-service-endpoint-01-get-market-data-service-subscriptions',
            'developer-interno/servizi/market-data-service-endpoint-02-post-market-data-service-subscriptions',
            'developer-interno/servizi/market-data-service-endpoint-03-delete-market-data-service-subscriptions-tic',
            'developer-interno/servizi/market-data-service-endpoint-04-post-market-data-service-subscriptions-resub',
            'developer-interno/servizi/market-data-service-endpoint-05-get-market-data-service-fields',
            'developer-interno/servizi/market-data-service-endpoint-06-post-market-data-service-fields',
            'developer-interno/servizi/market-data-service-endpoint-07-get-market-data-service-ibkr-status',
            'developer-interno/servizi/market-data-service-endpoint-08-get-market-data-service-snapshot-loop',
            'developer-interno/servizi/market-data-service-endpoint-09-post-market-data-service-snapshot-loop',
            'developer-interno/servizi/market-data-service-endpoint-10-delete-market-data-service-snapshot-loop',
            'developer-interno/servizi/market-data-service-endpoint-11-put-market-data-service-snapshot-interval',
          ],
        },
        {
          type: 'category',
          label: 'redis-ws-bridge',
          link: {type: 'doc', id: 'developer-interno/servizi/redis-ws-bridge'},
          items: [
            'developer-interno/servizi/redis-ws-bridge-endpoint-01-get-ws-upgrade-redis-ws-bridge-ws',
            'developer-interno/servizi/redis-ws-bridge-endpoint-02-get-redis-ws-bridge-status-health',
            'developer-interno/servizi/redis-ws-bridge-endpoint-03-get-redis-ws-bridge-status-clients',
            'developer-interno/servizi/redis-ws-bridge-endpoint-04-get-redis-ws-bridge-status-metrics',
            'developer-interno/servizi/redis-ws-bridge-endpoint-05-get-redis-ws-bridge-status-bus',
            'developer-interno/servizi/redis-ws-bridge-endpoint-06-get-redis-ws-bridge-status-communicationchan',
            'developer-interno/servizi/redis-ws-bridge-endpoint-07-put-redis-ws-bridge-status-communicationchan',
            'developer-interno/servizi/redis-ws-bridge-endpoint-08-get-redis-ws-bridge-status-loglevel',
            'developer-interno/servizi/redis-ws-bridge-endpoint-09-put-redis-ws-bridge-status-loglevel',
          ],
        },
        {
          type: 'category',
          label: 'ibkr-bridge',
          link: {type: 'doc', id: 'developer-interno/servizi/ibkr-bridge'},
          items: [
            'developer-interno/servizi/ibkr-bridge-endpoint-01-all-ibkr-bridge-mirror',
            'developer-interno/servizi/ibkr-bridge-endpoint-02-get-ibkr-bridge-accounts',
            'developer-interno/servizi/ibkr-bridge-endpoint-03-get-ibkr-bridge-account',
            'developer-interno/servizi/ibkr-bridge-endpoint-04-get-ibkr-bridge-status-health',
            'developer-interno/servizi/ibkr-bridge-endpoint-05-get-ibkr-bridge-status-info',
            'developer-interno/servizi/ibkr-bridge-endpoint-06-get-ibkr-bridge-status-communicationchannels',
            'developer-interno/servizi/ibkr-bridge-endpoint-07-put-ibkr-bridge-status-communicationchannels',
          ],
        },
        {
          type: 'category',
          label: 'ibkr-keepalive',
          link: {type: 'doc', id: 'developer-interno/servizi/ibkr-keepalive'},
          items: [
            'developer-interno/servizi/ibkr-keepalive-endpoint-01-get-ibkr-keepalive-release',
            'developer-interno/servizi/ibkr-keepalive-endpoint-02-get-ibkr-keepalive-settings',
            'developer-interno/servizi/ibkr-keepalive-endpoint-03-put-ibkr-keepalive-settings',
            'developer-interno/servizi/ibkr-keepalive-endpoint-04-post-ibkr-keepalive-settings-reload',
            'developer-interno/servizi/ibkr-keepalive-endpoint-05-put-ibkr-keepalive-connect',
            'developer-interno/servizi/ibkr-keepalive-endpoint-06-delete-ibkr-keepalive-connect',
            'developer-interno/servizi/ibkr-keepalive-endpoint-07-get-ibkr-keepalive-dblogger',
            'developer-interno/servizi/ibkr-keepalive-endpoint-08-put-ibkr-keepalive-dblogger-status',
            'developer-interno/servizi/ibkr-keepalive-endpoint-09-get-ibkr-keepalive-status-health',
            'developer-interno/servizi/ibkr-keepalive-endpoint-10-get-ibkr-keepalive-status-info',
          ],
        },
        {
          type: 'category',
          label: 'alertingservice',
          link: {type: 'doc', id: 'developer-interno/servizi/alertingservice'},
          items: [
            'developer-interno/servizi/alertingservice-endpoint-01-all-alertingservice-alerting-rules',
            'developer-interno/servizi/alertingservice-endpoint-02-all-alertingservice-alerting-rules-id',
            'developer-interno/servizi/alertingservice-endpoint-03-all-alertingservice-alerting-state',
            'developer-interno/servizi/alertingservice-endpoint-04-all-alertingservice-alerting-deliveries',
            'developer-interno/servizi/alertingservice-endpoint-05-post-alertingservice-alerting-rules-reload',
            'developer-interno/servizi/alertingservice-endpoint-06-get-alertingservice-events-catalog',
            'developer-interno/servizi/alertingservice-endpoint-07-post-alertingservice-email-send',
            'developer-interno/servizi/alertingservice-endpoint-08-post-alertingservice-whatsapp-send',
            'developer-interno/servizi/alertingservice-endpoint-09-post-alertingservice-whatsapp-template',
          ],
        },
        {
          type: 'category',
          label: 'scheduler',
          link: {type: 'doc', id: 'developer-interno/servizi/scheduler'},
          items: [
            'developer-interno/servizi/scheduler-endpoint-reload',
            'developer-interno/servizi/scheduler-endpoint-jobs-list',
            'developer-interno/servizi/scheduler-endpoint-jobs-create',
            'developer-interno/servizi/scheduler-endpoint-jobs-update',
            'developer-interno/servizi/scheduler-endpoint-jobs-last-run-update',
            'developer-interno/servizi/scheduler-endpoint-job-delete',
            'developer-interno/servizi/scheduler-endpoint-job-last-run-read',
            'developer-interno/servizi/scheduler-endpoint-job-run',
          ],
        },
        {
          type: 'category',
          label: 'tickerscanner',
          link: {type: 'doc', id: 'developer-interno/servizi/tickerscanner'},
          items: [
            'developer-interno/servizi/tickerscanner-endpoint-01-post-tickerscanner-fundamentals-ranking-dail',
            'developer-interno/servizi/tickerscanner-endpoint-02-get-tickerscanner-fundamentals-ranking-daily',
            'developer-interno/servizi/tickerscanner-endpoint-03-post-tickerscanner-universe-scan',
            'developer-interno/servizi/tickerscanner-endpoint-04-post-tickerscanner-universe-scan-force',
            'developer-interno/servizi/tickerscanner-endpoint-05-get-tickerscanner-universe-scan-jobs',
            'developer-interno/servizi/tickerscanner-endpoint-06-get-tickerscanner-universe-scan-status-jobid',
            'developer-interno/servizi/tickerscanner-endpoint-07-delete-tickerscanner-universe-scan-jobs-jobi',
            'developer-interno/servizi/tickerscanner-endpoint-08-get-tickerscanner-universe',
            'developer-interno/servizi/tickerscanner-endpoint-09-get-tickerscanner-universe-symbol',
            'developer-interno/servizi/tickerscanner-endpoint-10-get-tickerscanner-screener',
            'developer-interno/servizi/tickerscanner-endpoint-11-get-tickerscanner-scan',
            'developer-interno/servizi/tickerscanner-endpoint-12-get-tickerscanner-scan-force',
            'developer-interno/servizi/tickerscanner-endpoint-13-get-tickerscanner-scan-status-jobid',
            'developer-interno/servizi/tickerscanner-endpoint-14-get-tickerscanner-scan-jobs',
            'developer-interno/servizi/tickerscanner-endpoint-15-delete-tickerscanner-scan-jobs-jobid',
            'developer-interno/servizi/tickerscanner-endpoint-16-post-tickerscanner-momentum-refresh',
            'developer-interno/servizi/tickerscanner-endpoint-17-get-tickerscanner-glossary-filename',
            'developer-interno/servizi/tickerscanner-endpoint-18-post-tickerscanner-fundamentals-update-marke',
            'developer-interno/servizi/tickerscanner-endpoint-19-get-tickerscanner-fundamentals-update-market',
            'developer-interno/servizi/tickerscanner-endpoint-20-delete-tickerscanner-fundamentals-update-mar',
            'developer-interno/servizi/tickerscanner-endpoint-21-get-tickerscanner-fundamentals-market-daily-',
            'developer-interno/servizi/tickerscanner-endpoint-22-crud-tickerscanner-fundamentals-market-daily',
            'developer-interno/servizi/tickerscanner-endpoint-23-post-tickerscanner-fundamentals-user-daily-s',
            'developer-interno/servizi/tickerscanner-endpoint-24-get-tickerscanner-fundamentals-user-daily-sc',
            'developer-interno/servizi/tickerscanner-endpoint-25-delete-tickerscanner-fundamentals-user-daily',
            'developer-interno/servizi/tickerscanner-endpoint-26-get-tickerscanner-fundamentals-jobs',
            'developer-interno/servizi/tickerscanner-endpoint-27-crud-tickerscanner-fundamentals-user-daily-s',
            'developer-interno/servizi/tickerscanner-endpoint-28-crud-tickerscanner-fundamentals-ticker-scan-',
            'developer-interno/servizi/tickerscanner-endpoint-29-get-tickerscanner-fundamentals-history',
            'developer-interno/servizi/tickerscanner-endpoint-30-get-tickerscanner-fundamentals-scores-daily-',
            'developer-interno/servizi/tickerscanner-endpoint-31-get-tickerscanner-fundamentals-scores-daily--2',
            'developer-interno/servizi/tickerscanner-endpoint-32-post-tickerscanner-internal-fundamentals-use',
            'developer-interno/servizi/tickerscanner-endpoint-33-get-tickerscanner-release',
            'developer-interno/servizi/tickerscanner-endpoint-34-get-tickerscanner-settings',
            'developer-interno/servizi/tickerscanner-endpoint-35-put-tickerscanner-settings',
            'developer-interno/servizi/tickerscanner-endpoint-36-post-tickerscanner-settings-reload',
            'developer-interno/servizi/tickerscanner-endpoint-37-put-tickerscanner-connect',
            'developer-interno/servizi/tickerscanner-endpoint-38-delete-tickerscanner-connect',
            'developer-interno/servizi/tickerscanner-endpoint-39-get-tickerscanner-dblogger',
            'developer-interno/servizi/tickerscanner-endpoint-40-put-tickerscanner-dblogger-status',
            'developer-interno/servizi/tickerscanner-endpoint-41-get-tickerscanner-status-health',
            'developer-interno/servizi/tickerscanner-endpoint-42-get-tickerscanner-status-info',
            'developer-interno/servizi/tickerscanner-endpoint-43-get-tickerscanner-status-metrics',
            'developer-interno/servizi/tickerscanner-endpoint-44-get-tickerscanner-status-loglevel',
            'developer-interno/servizi/tickerscanner-endpoint-45-put-tickerscanner-status-loglevel',
            'developer-interno/servizi/tickerscanner-endpoint-46-get-tickerscanner-status-communicationchanne',
            'developer-interno/servizi/tickerscanner-endpoint-47-put-tickerscanner-status-communicationchanne',
          ],
        },
        {
          type: 'category',
          label: 'servicecontrolplane',
          link: {type: 'doc', id: 'developer-interno/servizi/servicecontrolplane'},
          items: [
            'developer-interno/servizi/servicecontrolplane-endpoint-01-get-servicecontrolplane-service-flags',
            'developer-interno/servizi/servicecontrolplane-endpoint-02-get-servicecontrolplane-service-flags-id',
            'developer-interno/servizi/servicecontrolplane-endpoint-03-post-servicecontrolplane-service-flags',
            'developer-interno/servizi/servicecontrolplane-endpoint-04-put-servicecontrolplane-service-flags-id',
            'developer-interno/servizi/servicecontrolplane-endpoint-05-delete-servicecontrolplane-service-flags-id',
          ],
        },
        {
          type: 'category',
          label: 'broker-executor-ibkr',
          link: {type: 'doc', id: 'developer-interno/servizi/broker-executor-ibkr'},
          items: [
            'developer-interno/servizi/broker-executor-ibkr-endpoint-01-get-broker-executor-ibkr-positions',
            'developer-interno/servizi/broker-executor-ibkr-endpoint-02-get-broker-executor-ibkr-orders',
            'developer-interno/servizi/broker-executor-ibkr-endpoint-03-get-broker-executor-ibkr-ws-status',
            'developer-interno/servizi/broker-executor-ibkr-endpoint-04-post-broker-executor-ibkr-order',
            'developer-interno/servizi/broker-executor-ibkr-endpoint-05-put-broker-executor-ibkr-order-orderid',
            'developer-interno/servizi/broker-executor-ibkr-endpoint-06-delete-broker-executor-ibkr-order-orderid',
          ],
        },
        {
          type: 'category',
          label: 'liquidity-manager',
          link: {type: 'doc', id: 'developer-interno/servizi/liquidity-manager'},
          items: [
            'developer-interno/servizi/liquidity-manager-endpoint-01-get-liquidity-manager-liquidity-score',
            'developer-interno/servizi/liquidity-manager-endpoint-02-post-liquidity-manager-liquidity-score-recom',
            'developer-interno/servizi/liquidity-manager-endpoint-03-get-liquidity-manager-liquidity-score-histor',
            'developer-interno/servizi/liquidity-manager-endpoint-04-get-liquidity-manager-liquidity-score-provid',
            'developer-interno/servizi/liquidity-manager-endpoint-05-get-liquidity-manager-liquidity-score-tasks',
            'developer-interno/servizi/liquidity-manager-endpoint-06-get-liquidity-manager-liquidity-score-tasks-',
            'developer-interno/servizi/liquidity-manager-endpoint-07-get-liquidity-manager-health',
          ],
        },
        {
          type: 'category',
          label: 'mcp-gateway',
          link: {type: 'doc', id: 'developer-interno/servizi/mcp-gateway'},
          items: [
            'developer-interno/servizi/mcp-gateway-endpoint-01-get-mcp-gateway-mcp-health',
            'developer-interno/servizi/mcp-gateway-endpoint-02-get-mcp-gateway-mcp-tools',
            'developer-interno/servizi/mcp-gateway-endpoint-03-post-mcp-gateway-mcp-call',
          ],
        },
        {
          type: 'category',
          label: 'market-simulator',
          link: {type: 'doc', id: 'developer-interno/servizi/market-simulator'},
          items: [
            'developer-interno/servizi/market-simulator-endpoint-01-post-market-simulator-session',
            'developer-interno/servizi/market-simulator-endpoint-02-get-market-simulator-session',
            'developer-interno/servizi/market-simulator-endpoint-03-delete-market-simulator-session',
            'developer-interno/servizi/market-simulator-endpoint-04-post-market-simulator-session-tick',
            'developer-interno/servizi/market-simulator-endpoint-05-post-market-simulator-subscriptions',
            'developer-interno/servizi/market-simulator-endpoint-06-get-market-simulator-subscriptions',
            'developer-interno/servizi/market-simulator-endpoint-07-delete-market-simulator-subscriptions',
            'developer-interno/servizi/market-simulator-endpoint-08-delete-market-simulator-subscriptions-symbol',
            'developer-interno/servizi/market-simulator-endpoint-09-get-market-simulator-candle',
            'developer-interno/servizi/market-simulator-endpoint-10-get-market-simulator-candle-range',
            'developer-interno/servizi/market-simulator-endpoint-11-post-market-simulator-candle-push',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '5. Release Notes',
      link: {type: 'doc', id: 'release-notes/overview'},
      items: [
        {
          type: 'category',
          label: 'Release 3.7.0',
          link: {type: 'doc', id: 'release-notes/release-3-7-0'},
          items: [],
        },
        {
          type: 'category',
          label: 'Release 3.5.0',
          link: {type: 'doc', id: 'release-notes/release-3-5-0'},
          items: [
            'release-notes/release-3-5-0-ibkr-login-desktop',
            'release-notes/release-3-5-0-servicecontrolplane',
          ],
        },
        {
          type: 'category',
          label: 'Release 3.4.0',
          link: {type: 'doc', id: 'release-notes/release-3-4-0'},
          items: [
            'release-notes/release-3-4-0-brokerexecutor-ibkr',
            'release-notes/release-3-4-0-capital-manager',
            'release-notes/release-3-4-0-datahub',
            'release-notes/release-3-4-0-decision-engine',
            'release-notes/release-3-4-0-liquidity-manager',
            'release-notes/release-3-4-0-mcp-gateway',
            'release-notes/release-3-4-0-tickerscanner',
          ],
        },
        'release-notes/template-release-notes',
      ],
    },
    {
      type: 'category',
      label: '6. Roadmap',
      link: {type: 'doc', id: 'roadmap/overview'},
      items: [
        {
          type: 'category',
          label: 'Decision Engine',
          items: [
            'roadmap/decision-engine/strategy-to-enter',
            'roadmap/decision-engine/gestione-ordini-aperti',
            'roadmap/decision-engine/custom-watch-analysis',
          ],
        },
        {
          type: 'category',
          label: 'Simulator',
          items: [
            'roadmap/simulator/market-simulator',
            'roadmap/simulator/market-simulator-implementation',
          ],
        },
        {
          type: 'category',
          label: 'Tickerscanner',
          items: [
            'roadmap/tickerscanner/pipe-system-refactor',
          ],
        },
        {
          type: 'category',
          label: 'Alerting Service',
          items: [
            'roadmap/alerting-service/improvements',
          ],
        },
        {
          type: 'category',
          label: 'Frontend',
          items: [
            'roadmap/frontend/mobile',
            'roadmap/frontend/miglioramenti',
          ],
        },
        {
          type: 'category',
          label: 'Development',
          items: [
            'roadmap/development/devspot-mobile-remote-development',
            'roadmap/development/migrate-to-gcp-registry',
            'roadmap/development/spot-instance-management',
          ],
        },
        'roadmap/crossservice-implementation',
        'roadmap/db-improvements',
        {
          type: 'category',
          label: 'ML Prediction',
          link: {type: 'doc', id: 'roadmap/ml-prediction-correlazione'},
          items: [
            'roadmap/ml-prediction-fonti-dati',
            'roadmap/ml-prediction-database',
            'roadmap/ml-prediction-ms-alt-data-collector',
            'roadmap/ml-prediction-ms-correlation-engine',
          ],
        },
        {
          type: 'category',
          label: 'Done',
          collapsed: true,
          items: [
            'roadmap/done/tickerscanner-service-improvements',
            'roadmap/done/cachemanager-bug-fix-e-miglioramenti',
            'roadmap/done/liquidity-manager-stabilizzazione-score',
            'roadmap/done/decision-engine-live-flow',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '7. Altra Documentazione',
      items: [
        'altra-documentazione/synology-cloudfare-tunnel-guide',
      ],
    },
  ],
};

export default sidebars;
